config/routes.rb
HWproduct::Application.routes.draw do
  get "home/index"

  devise_scope :user do
 get "/login" => "devise/sessions#new",:as=>:login
 match "/logout" => "devise/sessions#destroy",:as=>:logout
 match "/register" => "devise/registrations#new",:as=>:sign_up
 match "/users/password/edit" =>"users/password#edit"
 end

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HWproduct</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 3.0 License

Name       : Reinstated
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20120326
-->
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<title>Reinstated by nodethirtythree + Free CSS Templates</title>
		<link href="http://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="/assets/style.css" />
		<script type="text/javascript" src="/assets/jquery-1.7.1.min.js"></script>
		<script type="text/javascript" src="/assets/jquery.dropotron-1.0.js"></script>
		<script type="text/javascript" src="/assets/init.js"></script>
	</head>
	<body>
		<div id="wrapper">
			<div id="splash">
				<img src="/assets/pic1.jpg" alt="" />
			</div>
			<div id="menu">
				<ul>
					<li><a href="/home/index">Homepage</a></li>
					<li>
						Services <span class="arrow"></span>
						<ul>
							<li class="first"><a href="#">Sed imperdiet</a></li>
							<li><a href="#">Libero felis dolor</a></li>
							<li>
								Pulvinar duis <span class="arrow"></span>
								<ul>
									<li class="first"><a href="#">Consequat et magna amet</a></li>
									<li><a href="#">Nullam aliquam ridiculus</a></li>
									<li><a href="#">Sed imperdiet adipiscing lorem</a></li>
									<li><a href="#">Feugiat sed imperdiet</a></li>
									<li class="last"><a href="#">Libero etiam felis dolor</a></li>
								</ul>
							</li>
							<li><a href="#">Cras nulla ridiculus</a></li>
							<li><a href="#">Feugiat imperdiet</a></li>
							<li class="last"><a href="#">Libero felis dolor</a></li>
						</ul>
					</li>
					<li><a href="#">About</a></li>
					<li>
						Clients <span class="arrow"></span>
						<ul>
							<li class="first"><a href="#">Sed imperdiet</a></li>
							<li><a href="#">Libero felis dolor</a></li>
							<li>
								Pulvinar duis <span class="arrow"></span>
								<ul>
									<li class="first"><a href="#">Consequat et magna amet</a></li>
									<li><a href="#">Nullam aliquam ridiculus</a></li>
									<li><a href="#">Sed imperdiet adipiscing lorem</a></li>
									<li><a href="#">Feugiat sed imperdiet</a></li>
									<li class="last"><a href="#">Libero etiam felis dolor</a></li>
								</ul>
							</li>
							<li><a href="#">Cras nulla ridiculus</a></li>
							<li><a href="#">Feugiat imperdiet</a></li>
							<li class="last"><a href="#">Libero felis dolor</a></li>
						</ul>
					</li>
					<li><a href="#">Photos</a></li>
					<li><a href="#">Links</a></li>
					<li class="last"><a href="#">Contact</a></li>
				</ul>
				<br class="clearfix" />
			</div>
			<div id="header">
				<div id="logo">
					<h1><a href="#">Reinstated</a></h1>
				</div>
				<div id="search">
					<form action="" method="post">
						<div>
							<input class="form-text" name="search" size="32" maxlength="64" />
						</div>
					</form>
				</div>
			</div>
			<div id="page">
				<div id="content">
					<div class="box">
						<h2>Welcome to Reinstated</h2>
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>
</div>
					<br class="clearfix" />
				</div>
				<div id="sidebar">
					<div class="box">
						<h3>Morbi pharetra</h3>
						<ul class="list">
							<li class="first"><a href="#">Pharetra massa convallis</a></li>
							<li><a href="#">Cras nulla ridiculus</a></li>
							<li><a href="#">Feugiat arcu tempus congue</a></li>
							<li><a href="#">Libero felis magna dolor</a></li>
							<li><a href="#">Pulvinar ut facilisis duis</a></li>
							<li><a href="#">Cras nulla ridiculus</a></li>
							<li><a href="#">Feugiat arcu volutpat congue</a></li>
							<li><a href="#">Libero felis dolor</a></li>
							<li class="last"><a href="#">Venenatis et vel duis</a></li>
						</ul>
					</div>
					<div class="box">
						<h3>Magna luctus</h3>
						<p>
							Ultrices odio amet diam sollicitudin primis penatibus. Ullamcorper nulla elementum aliquam dui a nisl montes.
						</p>
					</div>
				</div>
				<br class="clearfix" />
			</div>
		</div>
		<div id="footer">
			&copy; 2012 Sitename.com. | Powered by <a href="#">admin</a> | Design by <a href="#">Team</a> .
		</div>
	</body>
</html>

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>